### ISSUE TITLE
VM Template fail for Azure SQL at SetupNavContainer.ps1

### ISSUE THREAD

**Issue by megel** [microsoft/nav-arm-templates#95] opened 2019-04-16 17:29 UTC
`SetupNavContainer.ps1` Fails for Azure SQL Databases at: 
![image](https://user-images.githubusercontent.com/15800069/56230534-c642f980-607c-11e9-9b2e-d4c4a89f08e5.png)

`settipngs.ps1`:
```PowerShell
$sqlServerType = "AzureSQL"
$azureSqlServer = "sqlierpbctest02.database.windows.net"
$appBacpacUri = "https://xxxxxxxx.blob.core.windows.net/db-backups/database.bacpac?st=2019-04-16T15%3A27%3A23Z&se=2022-04-17T15%3A27%3A00Z&sp=rl&sv=2018-03-28&sr=b&sig=THMFG%2FH1ydLLYWJmEEEEEEE2B%2FSj4dN8QmLTOWuYo3c%3D"
$tenantBacpacUri = ""
$includeAppUris = ""
$enableSymbolLoading = "Yes"
$clickonce = "No"
$enableTaskScheduler = "Yes"
$licenseFileUri = ""
$publicDnsName = "xxxxxx.westeurope.cloudapp.azure.com"
$workshopFilesUrl = ""
$style = "demo"
$RunWindowsUpdate = "Yes"
$AssignPremiumPlan = "No"
$CreateTestUsers = "No"
$CreateAadUsers = "No"
$Multitenant = "No"
$WindowsInstallationType = "Server"
$WindowsProductName = "Windows Server 2019 Datacenter"
```

Error:
![image](https://user-images.githubusercontent.com/15800069/56230507-b3302980-607c-11e9-9c34-1fd88f4d90db.png)

**Comment by megel** [comment] 2019-04-16 17:32
Changing this script inside of the VM helps:

```PowerShell
if ($sqlServerType -eq "AzureSQL") {
    if (Test-Path "c:\demo\objects.fob" -PathType Leaf) {
        Log "Importing c:\demo\objects.fob to container"
        Import-ObjectsToNavContainer -containerName $containerName -objectsFile "c:\demo\objects.fob" -sqlCredential $azureSqlCredential
    }
### >> CHANGED
    # Check for Multitenant
    if ($multitenant -eq "Yes") {
        New-NavContainerTenant -containerName $containerName -tenantId "default" -sqlCredential $azureSqlCredential
    }    
    # Included:  -ErrorAction Continue
    New-NavContainerNavUser -containerName $containerName -tenant "default" -Credential $credential -AuthenticationEmail $Office365UserName -ChangePasswordAtNextLogOn:$false -PermissionSetId "SUPER" -ErrorAction Continue
### <<
} else {
    if (Test-Path "c:\demo\objects.fob" -PathType Leaf) {
        Log "Importing c:\demo\objects.fob to container"
        $sqlCredential = New-Object System.Management.Automation.PSCredential ( "sa", $credential.Password )
        Import-ObjectsToNavContainer -containerName $containerName -objectsFile "c:\demo\objects.fob" -sqlCredential $sqlCredential
    }
}
```

**Comment by freddydk** [comment] 2019-04-16 18:42
azure sql was intended for multi-tenancy only,
So you are saying that it works?

**Comment by megel** [comment] 2019-04-16 19:33
It seams to me. However the AzureSQL database was created and the container id's working after this change. I will create some scripts to import / export the database for CD maybe in waldos pull request of nav container helper are some snippets.

**Comment by megel** [comment] 2019-04-16 19:35
When I switched my laptop, I can create a pull request 😂 too.

**Comment by megel** [comment] 2019-04-23 19:16
@freddydk the template seams now to fail during Import of the bacpac file. I created the backup with `Export-NavContainerDatabaseAsBacpac`. The bacpac file is OK, because, I can import into Azure SQL - alfter the template has failed :/

![image](https://user-images.githubusercontent.com/15800069/56609170-c018c400-660c-11e9-9395-af2061a61d9a.png)

Any suggestion?

**Comment by megel** [comment] 2019-04-24 07:49
OK, I discovered, the bacpac wasn't imported into Azure SQL too :(
This means, `Export-NavContainerDatabaseAsBacpac` from `NavContainerHelper` does not create a baclup for AzureSQL from an SQL Express database.

**Comment by megel** [comment] 2019-04-24 14:10
OK, I have tried these steps:

1) Export database from Container (Cronus) with `Export-NavContainerDatabaseAsBacpac` from `NavContainerHelper`:
  - Import in AzureSQL from ARM template: **fails**
  - Import in AzureSQL from Azure Portal: **fails**
2) Export database from Container (Cronus) with SQL Server Management Studio 18 (RC1)
  - Import in AzureSQL from ARM template: **fails**
  - Import in AzureSQL from Azure Portal: **OK**
    *after ARM has failed, but before `SetupNavContainer.ps1` in  VM was finished :)*
     --> ARM Template fail partialy, but **VM is OK**

Finally, the ARM template and `SetupNavContainer.ps1` works, **WHEN** you are able to replace the *App* database during deployment.

**But**

on Landing Page:
![image](https://user-images.githubusercontent.com/15800069/56665581-9b732980-66aa-11e9-849a-336e3294c23e.png)

inside of VM:
![image](https://user-images.githubusercontent.com/15800069/56665712-da08e400-66aa-11e9-825d-9198e3bf1f4a.png)

`Get-NavContainerServerConfiguration navserver`:

```powershell
PS C:\ProgramData\navcontainerhelper> Get-NavContainerServerConfiguration navserver


ContainerName                                   : navserver
NetworkProtocol                                 : Default
DatabaseServer                                  : localhost
DatabaseInstance                                : SQLEXPRESS
DatabaseName                                    : Cronusde
EnableSqlConnectionEncryption                   : false
TrustSQLServerCertificate                       : false
ServerInstance                                  : NAV
EnableSqlInformationDebugger                    : true
AmountOfSqlStatementsInDebugger                 : 10
EnableLongRunningSqlStatementsInDebugger        : true
LongRunningSqlStatementsInDebuggerThreshold     : 500
ClientServicesPort                              : 7046
SOAPServicesPort                                : 7047
ODataServicesPort                               : 7048
ManagementServicesPort                          : 7045
ManagementServicesEnabled                       : true
ClientServicesEnabled                           : true
DeveloperServicesPort                           : 7049
DeveloperServicesEnabled                        : true
DeveloperServicesSSLEnabled                     : true
ExtensionAllowedTargetLevel                     : Internal
ReportPDFFontEmbedding                          : true
ReportAppDomainIsolation                        : true
EnableSaveToWordForRdlcReports                  : true
EnableSaveToExcelForRdlcReports                 : true
EnableSaveFromReportPreview                     : true
CompileBusinessApplicationAtStartup             : true
SOAPServicesEnabled                             : true
ODataServicesEnabled                            : true
ODataServicesV3EndpointEnabled                  : true
ODataServicesV4EndpointEnabled                  : true
SOAPServicesSSLEnabled                          : true
ODataServicesSSLEnabled                         : true
ODataMaxConnections                             : 0
ODataMaxConnectionsPerTenant                    : 0
DeltaServiceClientTimeout                       : 00:02:00
ODataServicesOperationTimeout                   : MaxValue
PublicODataBaseUrl                              : https://CUSTOMER.westeurope.cloudapp.azure.com:7048/NAV/OData
PublicSOAPBaseUrl                               : https://CUSTOMER.westeurope.cloudapp.azure.com:7047/NAV/WS
PublicWebBaseUrl                                : https://CUSTOMER.westeurope.cloudapp.azure.com/NAV/
PublicWinBaseUrl                                : DynamicsNAV://CUSTOMER.westeurope.cloudapp.azure.com:7046/NAV/
DefaultClient                                   : Web
ServicesOptionFormat                            : OptionCaption
ServicesLanguage                                : en-US
CalendarTwoDigitYearMax                         : -1
SOAPServicesMaxMsgSize                          : 1024
ServicesUseNTLMAuthentication                   : false
ServicesDefaultTimeZone                         : UTC
ServicesDefaultCompany                          :
ODataServicesMaxPageSize                        : 1000
ClientServicesOperationTimeout                  : MaxValue
ClientServicesProtectionLevel                   : EncryptAndSign
MaxConcurrentCalls                              : 1000
ClientServicesMaxConcurrentConnections          : 500
ClientServicesReconnectPeriod                   : 00:10:00
ClientServicesMaxNumberOfOrphanedConnections    : 20
ClientServicesCompressionThreshold              : 64
ClientServicesMaxUploadSize                     : 150
EnableDebugging                                 : false
DebuggingAllowed                                : true
ClientServicesMaxItemsInObjectGraph             : 512
ClientServicesChunkSize                         : 28
ClientServicesProhibitedFileTypes               : ade;adp;asp;bas;bat;chm;cmd;com;cpl;csh;exe;fxp;gadget;hlp;hta;inf;in
                                                  s;isp;its;js;jse;ksh;lnk;mad;maf;mag;mam;maq;mar;mas;mat;mau;mav;maw;
                                                  mda;mdb;mde;mdt;mdw;mdz;msc;msi;msp;mst;ops;pcd;pif;prf;prg;pst;reg;s
                                                  cf;scr;sct;shb;shs;url;vb;vbe;vbs;vsmacros;vss;vst;vsw;ws;wsc;wsf;wsh
ClientServicesAllowedFileTypes                  :
NASServicesStartupCodeunit                      :
NASServicesRunWithAdminRights                   : false
EnableDeadlockMonitoring                        : true
NASServicesStartupMethod                        :
NASServicesStartupArgument                      :
NASServicesEnableDebugging                      : false
ClientServicesCredentialType                    : NavUserPassword
UIElementRemovalOption                          : LicenseFileAndUserPermissions
ClientServicesTokenSigningKey                   :
ClientServicesFederationMetadataLocation        :
ServicesCertificateThumbprint                   : 5EA212A21BE4D8D6C39476E77122F91E7B109268
ServicesCertificateValidationEnabled            : false
DisableTokenSigningCertificateValidation        : false
TokenSigningCertificateValidationMode           : IssuerNameValidation
DataCacheSize                                   : 10
SessionEventTableRetainInterval                 : 90.00:00:00
NonInteractiveSessionsLogRetainInterval         : 5.00:00:00
SqlCommandTimeout                               : 00:30:00
SqlConnectionTimeout                            : 00:01:30
BufferedInsertEnabled                           : true
DisableSmartSql                                 : false
EnableFullALFunctionTracing                     : false
Multitenant                                     : False
SqlConnectionIdleTimeout                        : 00:05:00
EnableALServerFileAccess                        : true
EnableApplicationChannelLog                     : true
EncryptionProvider                              : LocalKeyFile
ExchangeAuthenticationMetadataLocation          :
AppIdUri                                        :
WSFederationLoginEndpoint                       :
AzureActiveDirectoryClientId                    :
AzureActiveDirectoryClientSecret                :
AzureActiveDirectoryClientCertificateThumbprint :
EnableMembershipEntitlement                     :
MaxRowsToExportToExcel                          : MaxValue
EnableTaskScheduler                             : true
TaskSchedulerMaximumConcurrentRunningTasks      : 10
ClientServicesKeepAliveInterval                 : 00:02:00
UseSimplifiedFilters                            : false
ExcelAddInAzureActiveDirectoryClientId          :
DisableWriteInsideTryFunctions                  : true
ExtendedSecurityTokenLifetime                   : 0
ClientServicesIdleClientTimeout                 : MaxValue
ODataEnableExcelAddInAnnotations                : true
NavHttpClientMaxResponseContentSize             : 150
NavHttpClientMaxTimeout                         : 00:05:00
SqlParametersByOrdinal                          : true
ClientBuildRestriction                          : WarnClient
TraceLevel                                      : Normal
ExternalTraceLevel                              : Error
EnableDataExportImport                          : true
MaxStreamReadSize                               : 1000000
ValidAudiences                                  :
DefaultLanguage                                 :
SupportedLanguages                              :
ApiServicesEnabled                              : True
ApiSubscriptionsEnabled                         : true
ApiSubscriptionExpiration                       : 3
ApiSubscriptionNotificationUrlTimeout           : 5000
ApiSubscriptionSendingNotificationTimeout       : 30000
ApiSubscriptionDelayTime                        : 30000
ApiSubscriptionMaxNumberOfNotifications         : 100
ApiSubscriptionMaxNumberOfSubscriptions         : 200
EnableSymbolLoadingAtServerStartup              : True
SqlLongRunningThreshold                         : 1000
SqlBulkImportBatchSize                          : 448
UseIncrementalCompanyDelete                     : true
TaskSchedulerSystemTaskStartTime                : 00:00:00
TaskSchedulerSystemTaskEndTime                  : 23:59:59
XmlMetadataCacheSize                            : 500
AllowSessionWhileSyncAndDataUpgrade             : false
SearchTimeout                                   : 00:00:10
OverwriteExistingTranslations                   : true
LockoutPolicyFailedAuthenticationCount          : 0
LockoutPolicyFailedAuthenticationWindow         : 0
ReplaceReportExecutionTimeWithClientTime        : true
UseFindMinusWhenPopulatingPage                  : true
DisableQueryHintOptimizeForUnknown              : false
DisableQueryHintForceOrder                      : true
DisableQueryHintLoopJoin                        : true
SecurityProtocol                                : Tls12
AzureKeyVaultClientId                           : 00000000-0000-0000-0000-000000000000
AzureKeyVaultClientCertificateStoreLocation     : LocalMachine
AzureKeyVaultClientCertificateStoreName         : My
AzureKeyVaultClientCertificateThumbprint        :
AzureKeyVaultKeyUri                             :
```

NO, Azure SQL is not working :(

**Comment by freddydk** [comment] 2019-04-24 14:12
I will have a look at this one of the next days

**Comment by megel** [comment] 2019-04-29 11:41
I found the problem:

```PowerShell
if ("$appBacpacUri" -ne "" -and "$tenantBacpacUri" -ne "") {
    if ("$sqlServerType" -eq "SQLExpress") {
        $additionalParameters += @("--env appbacpac=$appBacpacUri",
                                   "--env tenantbacpac=$tenantBacpacUri")
    } else {
        Log "using $azureSqlServer as database server"
        $params += @{ "databaseServer"     = "$azureSqlServer"
                      "databaseInstance"   = ""
                      "databaseName"       = "App"
                      "databaseCredential" = $azureSqlCredential }
        $multitenant = "Yes"
    }
}
```

In my case, I use only `$appBacpacUri` so I'll change the condition into:

```PowerShell
# Enabled the setup of Azure SQL for existing $appBacpacUri 
if ("$appBacpacUri" -ne "") {
    if ("$sqlServerType" -eq "SQLExpress" -and "$tenantBacpacUri" -ne "") {
        $additionalParameters += @("--env appbacpac=$appBacpacUri",
                                   "--env tenantbacpac=$tenantBacpacUri")
    } else {
        Log "using $azureSqlServer as database server"
        $params += @{ "databaseServer"     = "$azureSqlServer"
                      "databaseInstance"   = ""
                      "databaseName"       = "App"
                      "databaseCredential" = $azureSqlCredential }
        # $tenantBacpacUri for check multi tenant included 
        if ("$tenantBacpacUri" -ne "") {
            $multitenant = "Yes"
        }
    }
}
```

**Comment by freddydk** [comment] 2019-12-22 22:53
is in dev branch, will be in master soon

**Comment by freddydk** [comment] 2019-12-25 07:40
Shipped

**Closed by freddydk** 2019-12-25 07:40 UTC
Labels: Under investigation, enhancement
