### ISSUE TITLE
Cannot connect to created web via Universal App / iOS App, using getbc

### ISSUE THREAD

**Issue by ichladil** [microsoft/nav-arm-templates#84] opened 2019-02-22 14:09 UTC
Using Universal Business Central App and/or iOS App I cannot connect to the BC web client end point. 
From the browser it works OK for both phone and desktop.

I choose _My Business Central is not in the cloud yet_ and provide the web url. It let us even authenticate and then it returns 

> Sorry, the page could not be found. - Please check the address and try again.

The URL used is like https://mydemo.westeurope.cloudapp.azure.com/NAV/

Config for getbc is pretty much all inclusive:
- Image: mcr.microsoft.com/businesscentral/onprem:cz
- AAD integration
- Custom license
- Windows Server 2019 with Containers

Any help/direction on how to make Universal App & Phone Client working with getbc out-of-the-box setup is greatly appreciated.

**Comment by freddydk** [comment] 2019-03-01 13:28
What docker container are you running?
It looks like the version of the universal app doesn't match the version of Business Central.

**Comment by ichladil** [comment] 2019-03-01 14:13
Docker container is: mcr.microsoft.com/businesscentral/onprem:cz
That same container works if I do not use AAD.

**Comment by kfuglsang** [comment] 2019-05-29 13:52
Im having the same issue with a non-docker onprem install using AAD. Web client works fine but universal app ends in "Sorry, the page could not be found" after successful login.
Still trying to find a way to debug whats happening. The traffic is TLS encrypted so I'm struggling to find the actual URL its trying to load.

**Comment by kfuglsang** [comment] 2019-06-03 07:06
Do we know what URL it is actually trying to load?

I have this issue on two different on-prem BC installs. Both using AAD but different BC builds.

**Comment by freddydk** [comment] 2019-12-10 07:57
Did you guys manage to solve this?

**Comment by kfuglsang** [comment] 2019-12-10 13:52
Never.
Had to spin up a separate server instance using NavUserPassword to get the customer running.

**Comment by freddydk** [comment] 2019-12-17 13:49
In the mobile app, you enter the URL of your service yourself - and your service will redirect to AAD signin. Just tried with https://fkaad.westeurope.cloudapp.azure.com/BC, which is an AzureVM with BC and letsencrypt. Works like a charm.
Will close this issue as the original issue seems not reproducable.
@kfuglsang if you have issues with non-docker setup with mobile apps, you should maybe try yammer or support.
thanks

**Closed by freddydk** 2019-12-17 13:49 UTC
Labels: Under investigation
